---
title: "simulation_all_in_one"
author: "Lin Yu"
date: "2024-02-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

## Simulation Scenario
The linear predictor is 
\[X_1+X_2+0.75X_3-0.75X_4+0.75X_5+X_1X_2-X_1X_2\]

Step one, generate the simulation datasets. number of features of 25, 50 and 100. To get sim_set1, sim_set2 and sim_set3, you need to run \texttt{R/00_simu_data_setup.R} . Also run \texttt{R/00_simu_data_setup_500test.R} to get 500 obs test set##
```{r include=FALSE}
## source('R/00_simu_data_setup.R') ## train data save as sim_set
seed = 2024
seed = 20310222
#seed = 20250222
#seed = 20260222
#seed = 20270222
#seed = 20280222
#seed = 20290222
source('R/00_simu_data_setup.R')
source('R/00_simu_data_setup_500test.R')

```


```{r}
#load("data/sim_set/sim_set1_2024-02-01.rdata")
source('R/helper_f.R')
# boot_lst <- sim_set1
sim_data <- TRUE

cov_interact <- TRUE #### for simulation data, do not have other demographic variables
method <- c('lasso',"ridge")
method <- c('lasso')
method <- c("ridge")
```

```{r eval=FALSE, include=FALSE}
t1 <- Sys.time() 
library(caret)
library(dplyr)
library(survival)
  m <- method
  k = 3
  model_out_all <- lapply(1:length(m), function(x) {
    lapply(1:length(boot_lst), function(y) {
      print(y)
      folds <- createFolds(boot_lst[[y]]$status, k = k, list = TRUE, returnTrain = FALSE)

      ## I want to know how many true effects are
      ## selected in each boot dataset
      selected_true <- c("X1","X2","X3","X4","X5") %in%
        (boot_lst[[y]] %>% colnames())

      X1X2 <- ifelse((selected_true[1]==TRUE & selected_true[2]==TRUE),
                     TRUE, FALSE )
      X3X4 <- ifelse((selected_true[3]==TRUE & selected_true[4]==TRUE),
                     TRUE, FALSE )

      boot_true_margin <- selected_true %>% sum()
      boot_true_inter <- sum(X1X2,X3X4)


      ## the validation performance
      lapply(1:length(folds),function(z){

        res <-  HDSI_model_f(boot_df_train = boot_lst[[y]][-folds[[z]],],
                             cov_interact = cov_interact,
                             # boot_df_test = boot_lst[[y]][folds[[z]],],
                             method = m[[x]])
        res$boot = y
        res$fold = -z
        res$boot_true_margin = boot_true_margin
        res$boot_true_inter = boot_true_inter
        res

      })
    })
  })
t2 <- Sys.time() 
t2 - t1
```

```{r eval=FALSE, include=FALSE}
 perf_tmp <- model_out_all[[1]] %>% bind_rows()
   
perf_onefold <-  perf_tmp[perf_tmp$fold==-1,]
```

```{r eval=FALSE, include=FALSE}
boot_true_margin_p <- perf_onefold %>% select(boot,boot_true_inter,boot_true_margin) %>% 
  unique() %>% 
  ggplot(aes(x = boot_true_margin))+
  geom_histogram()+
  theme_bw()

ggsave(boot_true_margin_p, file='boot_true_margin_p15.png',dpi = 300)
```

```{r eval=FALSE, include=FALSE}
boot_true_inter_p <- perf_onefold %>% select(boot,boot_true_inter,boot_true_margin) %>% 
  unique() %>% 
  ggplot(aes(x = boot_true_inter))+
  geom_histogram()+
  theme_bw()
ggsave(boot_true_inter_p, file='boot_true_inter_p15.png',dpi = 300)
```

```{r eval=FALSE, include=FALSE}
perf_onefold %>% select(boot,boot_true_inter,boot_true_margin) %>% 
  unique() %>% 
  ggplot(aes(x = boot_true_inter))+
  geom_histogram()
```


```{r eval=FALSE, include=FALSE}

library(stringr)

fe_star <-  perf_onefold %>%  group_by(model_cindex) %>% summarise(n=n())
      ### compute min_cindex
      min_cindex <- perf_onefold %>%
        group_by(varname) %>%
        summarise(min_cindex = min(model_cindex)) %>%
        mutate(
          miu_min_cindex = mean(min_cindex),
          # sigma_min_cindex = sqrt(mean((min_cindex - miu_min_cindex)^2) / (fe_star$n %>% unique() - 1)),
          sd_min_cindex = sd(min_cindex),
          Rf = Rf, ## hyperparameter
          include_yn = min_cindex > (miu_min_cindex + Rf * sd_min_cindex)
        )
     ### compute coef estimate and CI
      beta_quantile <- perf_onefold %>%
        group_by(varname) %>%
        mutate(quantile = qtl) %>% ## quantile is a hyperparameter
        summarise(
          qtl = qtl,
          beta_hat = mean(X1),
          qtl_lower = quantile(X1, probs = qtl/2),
          qtl_upper = quantile(X1, probs = 1 - (qtl /2) ),
          include0_yn = !(((qtl_lower <= 0) & (0 <= qtl_upper)) | ((qtl_upper <= 0) & (0 <= qtl_lower)))
        )

      ### join beta and cindex in a dataframe; filter selected features
      perf_tmp  <- full_join(beta_quantile, min_cindex, by = "varname") 
      
      perf <-  perf_tmp %>% 
        filter(include0_yn == TRUE & include_yn == TRUE)

      ### adding back main effect if only interaction terms are selected
      included_inter <- perf$varname[str_detect(perf$varname, ":")] ## detect interaction terms

      ## detect main effect terms from interaction
      included_inter1 <- stringr::str_split(included_inter, ":") %>% unlist()

      ## final selected features
      included_fe <- c(perf$varname, included_inter1) %>% unique()
      
      perf  <- perf_tmp %>% 
        filter(varname %in% included_fe)
      
      included_fe
      perf
      #included_fe
```

```{r}
t1 = Sys.time() 
Rf = 2.5
qtl = 0.05
internal_res <- inter_perf_f(boot_lst=sim_set1[[1]],
cov_interact = cov_interact, k = 2,  method = method,
  qtl = qtl, Rf =Rf)

t2 = Sys.time() 

t2 - t1

save(internal_res,file= paste0("internal_res",Sys.time(),".rdata"))

```

```{r}

internal_res[[2]]
internal_res[[3]]
```
```{r echo=TRUE}
t1 = Sys.time() 
external_res<- inter_perf_f(boot_lst=sim_set1_test[[1]], ## 1 代表 25 个feature； [[2]]代表50个feature； [[3]] 代表100个feature
cov_interact = cov_interact, k = 1,  method = method,
  qtl = qtl, Rf = Rf)

save(external_res,file= paste0("external_res",Sys.time(),".rdata"))

t2 = Sys.time() 

t2 - t1
```

```{r}
external_res[[2]]
external_res[[3]]
```

The lung_boot_lst is the bootstrap list that well be used
```{r eval=FALSE, include=FALSE}
load('output/uni_cox_top200.rdata')
load('data/cox_dat.rdata')
source('R/helper_f.R')

reg_dat <-cox_dat %>%
  select("time", "status", "age_at_diagnosis", "cancer_stage",
         (uni_cox_top200$var_name))

reg_dat50 <- reg_dat[,c(1:54)]
reg_dat <- reg_dat50
set.seed(20240123)
trainIndex <- createDataPartition(reg_dat$status,
                                  p = 0.8, list = FALSE)

trainingSet <- reg_dat[trainIndex,]
testSet <- reg_dat[-trainIndex,]

#save(trainingSet,file = 'output/trainingSet.rdata')
#save(testSet,file = 'output/testSet.rdata')

lung_boot_lst <- boot_f1(
  df = trainingSet,
  nboot = 100,
  boot_ft = 20,
  gene_index = 5,
  cov_vars = c('age_at_diagnosis','cancer_stage'),
  seed = 20231106
)

lung_boot_lst <- boot_f1(
  df = trainingSet,
  nboot = 1000,
  boot_ft = 15,
  gene_index = 5,
  cov_vars = c('age_at_diagnosis','cancer_stage'),
  seed = 20231106
)
```


