#install.packages("dplyr",repos = "https://cloud.r-project.org/")


# install.packages("survival",repos = "https://cloud.r-project.org/")
# install.packages("stringr",repos = "https://cloud.r-project.org/")
# install.packages("survival",repos = "https://cloud.r-project.org/")
# install.packages("caret",repos = "https://cloud.r-project.org/")
# install.packages("ggplot2",repos = "https://cloud.r-project.org/")
# install.packages("hrbrthemes",repos = "https://cloud.r-project.org/")
# install.packages("dplyr",repos = "https://cloud.r-project.org/")
# install.packages("tidyr",repos = "https://cloud.r-project.org/")
# install.packages("viridis",repos = "https://cloud.r-project.org/")
# install.packages("ggridges",repos = "https://cloud.r-project.org/")
# install.packages("tidyverse",repos = "https://cloud.r-project.org/")
# install.packages("parallel",repos = "https://cloud.r-project.org/")
library(pbapply)
library(glmnet)
library(dplyr)
library(survival)
library(stringr)
library(survival)
library(caret)
library(ggplot2)
library(hrbrthemes)
library(dplyr)
library(tidyr)
library(viridis)
library(ggridges)
library(tidyverse)
library(parallel)

